/* Copyright (c) 2026 Red Hat, Inc.
 * SPDX-License-Identifier: EPL-2.0
 *
 * fficonfig.h — hand-generated for linux-s390x
 * Replaces the file normally generated by autoconf ./configure.
 * All HAVE_xxx values are standard POSIX features present on Linux.
 */
#ifndef LIBFFI_CONFIG_H
#define LIBFFI_CONFIG_H

#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_DLFCN_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_LONG_DOUBLE 1
/* s390x long double is always 16-byte IEEE 754 binary128 — no ABI variants */
#define HAVE_LONG_DOUBLE_VARIANT 0
#define HAVE__BOOL 1
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define FFI_CLOSURES 1
#define FFI_EXEC_TRAMPOLINE_TABLE 0
#define FFI_MMAP_EXEC_WRIT 0
#define FFI_NO_STRUCTS 0
#define LT_OBJDIR ".libs/"
#define PACKAGE "libffi"
#define PACKAGE_BUGREPORT "http://github.com/libffi/libffi/issues"
#define PACKAGE_NAME "libffi"
#define PACKAGE_STRING "libffi 3.4.6"
#define PACKAGE_TARNAME "libffi"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "3.4.6"
#define VERSION "3.4.6"
#define STDC_HEADERS 1

#endif /* LIBFFI_CONFIG_H */
