#!/usr/bin/env python3
# Copyright (c) 2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

"""
Patch ffi-napi's binding.gyp to use the system libffi instead of the bundled copy.

ffi-napi 4.0.3 bundles libffi 3.4.2 which contains K&R-style function definitions
in deps/libffi/src/ and deps/libffi/include/ that GCC 13 rejects with:
  error: old-style parameter declarations in prototyped function definition

The system libffi-dev on Ubuntu 24.04 (libffi 3.4.6) has clean ANSI C declarations.
This script:
  1. Copies system fficonfig.h and ffi.h into deps/libffi/include/ so that
     src/ffi.cc's `#include "fficonfig.h"` and the existing include path resolves.
  2. Removes the dependency on deps/libffi/libffi.gyp:ffi (bundled libffi build)
  3. Adds -lffi to the libraries list to link against the system libffi.so

Note: we keep deps/libffi/include/ path intact in binding.gyp because ffi-napi's
src/ffi.cc uses #include "fficonfig.h" (relative search) and the existing include_dirs
already point to deps/libffi/include/. We just replace the header files contents.
"""

import os
import platform
import re
import shutil
import sys

# Resolve binding.gyp relative to this script's location, falling back to CWD.
_script_dir = os.path.dirname(os.path.abspath(__file__))
BINDING_GYP = os.path.join(_script_dir, "binding.gyp")
if not os.path.exists(BINDING_GYP):
    BINDING_GYP = "binding.gyp"
if not os.path.exists(BINDING_GYP):
    print(f"ERROR: binding.gyp not found", file=sys.stderr)
    sys.exit(1)

# Determine the multiarch directory for system libffi headers.
machine = platform.machine()
machine_to_multiarch = {
    "s390x":    "s390x-linux-gnu",
    "ppc64le":  "powerpc64le-linux-gnu",
    "x86_64":   "x86_64-linux-gnu",
    "aarch64":  "aarch64-linux-gnu",
}
multiarch = machine_to_multiarch.get(machine, f"{machine}-linux-gnu")
sys_include = f"/usr/include/{multiarch}"
print(f"System arch={machine}, multiarch include: {sys_include}")

# Step 1: Copy system fficonfig.h and ffi.h into deps/libffi/include/.
# src/ffi.cc uses `#include "fficonfig.h"` and binding.gyp's include_dirs
# already include 'deps/libffi/include/', so the files just need to be there.
ffi_include_dir = os.path.join(_script_dir, "deps", "libffi", "include")
os.makedirs(ffi_include_dir, exist_ok=True)

for fname in ("ffi.h", "ffitarget.h"):
    src = os.path.join(sys_include, fname)
    dst = os.path.join(ffi_include_dir, fname)
    if os.path.exists(src):
        shutil.copy2(src, dst)
        print(f"  Copied {src} → {dst}")
    else:
        src2 = os.path.join("/usr/include", fname)
        if os.path.exists(src2):
            shutil.copy2(src2, dst)
            print(f"  Copied {src2} → {dst} (fallback)")
        else:
            print(f"  NOTE: {fname} not found (non-fatal for {fname})")

# fficonfig.h is NOT shipped by libffi-dev as a public header (it is generated by
# autoconf at build time). If a pre-made fficonfig-s390x.h was placed alongside
# this script, copy it. Otherwise write a minimal inline version.
fficonfig_dst = os.path.join(ffi_include_dir, "fficonfig.h")
fficonfig_src = os.path.join(_script_dir, "fficonfig-s390x.h")
if os.path.exists(fficonfig_src):
    shutil.copy2(fficonfig_src, fficonfig_dst)
    print(f"  Copied {fficonfig_src} → {fficonfig_dst}")
elif not os.path.exists(fficonfig_dst):
    # Write a minimal fficonfig.h for Linux s390x inline.
    # All values are standard POSIX features available on Linux.
    minimal_fficonfig = """\
/* fficonfig.h — generated by patch-ffi-napi.py for linux-{arch} */
#ifndef LIBFFI_CONFIG_H
#define LIBFFI_CONFIG_H
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_DLFCN_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_LONG_DOUBLE 1
#define HAVE_LONG_DOUBLE_VARIANT 0
#define HAVE__BOOL 1
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define FFI_CLOSURES 1
#define FFI_EXEC_TRAMPOLINE_TABLE 0
#define FFI_MMAP_EXEC_WRIT 0
#define FFI_NO_STRUCTS 0
#define LT_OBJDIR ".libs/"
#define PACKAGE "libffi"
#define PACKAGE_BUGREPORT "http://github.com/libffi/libffi/issues"
#define PACKAGE_NAME "libffi"
#define PACKAGE_STRING "libffi 3.4.6"
#define PACKAGE_TARNAME "libffi"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "3.4.6"
#define VERSION "3.4.6"
#define STDC_HEADERS 1
#endif /* LIBFFI_CONFIG_H */
""".format(arch=machine)
    open(fficonfig_dst, "w").write(minimal_fficonfig)
    print(f"  Wrote inline fficonfig.h → {fficonfig_dst}")

# Step 2: Patch binding.gyp — remove bundled libffi GYP dep, add -lffi library flag.
text = open(BINDING_GYP).read()

old_dep = '"deps/libffi/libffi.gyp:ffi"'
if old_dep not in text:
    print("NOTE: bundled libffi dependency not found in binding.gyp — may already be patched")
else:
    # Remove the dependency entry (with preceding comma)
    text = re.sub(r',?\s*"deps/libffi/libffi\.gyp:ffi"\s*,?', '', text)
    # Clean up any trailing commas before ]
    text = re.sub(r',(\s*\])', r'\1', text)
    print("Removed bundled libffi GYP dependency from binding.gyp")

# Add deps/libffi/include to include_dirs so that src/ffi.cc finds fficonfig.h and ffi.h.
# Also add system libffi include dir and link -lffi.
# Add -fpermissive to cflags_cc to allow function pointer type conversions that changed
# in Node.js 24 (napi_get_uv_event_loop signature changed from napi_env to
# node_api_basic_env; get-uv-event-loop-napi-h uses the old signature).
if "deps/libffi/include" not in text:
    text = text.replace(
        "'include_dirs': [",
        (
            "'libraries': ['-lffi'],\n"
            "    'cflags_cc': ['-fpermissive'],\n"
            "    'include_dirs': [\n"
            "      'deps/libffi/include',\n"
            f"      '{sys_include}',"
        ),
        1,
    )
    print(f"Added deps/libffi/include, {sys_include}, -lffi, -fpermissive to binding.gyp")
elif "'-lffi'" not in text and '"-lffi"' not in text:
    text = text.replace(
        "'dependencies': [",
        "'libraries': ['-lffi'],\n    'dependencies': [",
        1,
    )
    print("Added -lffi to binding.gyp libraries")

open(BINDING_GYP, "w").write(text)
print("binding.gyp patched successfully")
